import Head from "next/head";
import Hero from "@/components/Home/Hero";
import Navbar from "@/components/Navbar";
import BlueExffect from "@/components/BlueEffect/BlueExffect";
import styled from "styled-components";
import VoiletEffect from "@/components/VoiletEffect/VoiletEffect";

const Wrapper = styled.div`
  width: 100%;
  overflow: hidden;
  position: absolute;
`;

const Container = styled.div`
  width: 90%;
  height: auto;
  margin: 0 auto;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BlueExffect />
      <Wrapper>
        <Container>
          <Navbar />
          <Hero />
        </Container>
      </Wrapper>
    </>
  );
}
