import Head from "next/head";
import Hero from "@/components/Home/Hero";
import Navbar from "@/components/Navbar";
import BlueExffect from "@/components/BlueEffect/BlueExffect";
import styled from "styled-components";
import VoiletEffect from "@/components/VoiletEffect/VoiletEffect";
import FeatureSection from "@/components/Home/FeatureSection";
import FeaturesOfFuture from "@/components/Home/FeaturesOfFuture";

const Wrapper = styled.div`
  width: 100%;
  overflow: hidden;
  position: absolute;
`;

const Container = styled.div`
  width: 90%;
  height: auto;
  margin: 0 auto;
`;
const FlexWrapper = styled.div`
  display: flex;
  max-width: 350px;
  margin: 5px auto;
  flex-direction: ${(props) => props.direction};
  justify-content: center;
  align-items: center;
  gap: 5px;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BlueExffect />
      <Wrapper>
        <Container>
          <Navbar />
          <Hero />
          <FeatureSection />
          <FeaturesOfFuture />
        </Container>
      </Wrapper>
    </>
  );
}
